### ISSUE TITLE
Update error message or set defaults for endpoint URLs in aks-set-context

### ISSUE THREAD

**Issue by pjsier** [Azure/k8s-actions#33]
In the `aks-set-context` command it's not clear that `activeDirectoryEndpointUrl` and `resourceManagerEndpointUrl` are required values in the Azure credentials, and the error message doesn't mention them.

I spent some time debugging this using an existing service principal which didn't have the same output as the one in the docs, and it might be more straightforward to either add those values to the error message or set defaults of "https://login.microsoftonline.com" and "https://management.azure.com/" if those will almost always be the values.

I'm happy to put in a PR for this if it would be helpful, and thanks for maintaining this repo! It was really helpful in getting started deploying to AKS with actions

**Comment by ds-ms** [comment]
The action is moved to `azure/aks-set-context` repo. I suggest you create a PR there! :)

**Comment by pjsier** [comment]
Ah looks like I missed that, thanks for the quick response! I'll close this then

**Comment by ds-ms** [comment]
Thanks, @pjsier you could refer me in the PR. I can help you merge it.
