### ISSUE TITLE
Namespace gets ignored

### ISSUE THREAD

**Issue by niekappartmedia** [Azure/k8s-actions#35]
I have the following problem:
When i add a secret to an existing namespace in the cluster: /usr/bin/kubectl create secret generic mysql-secret --from-literal=MYSQL_DATABASE=*** --from-literal=MYSQL_USERNAME=*** -- from-literal=MYSQL_PASSWORD=*** -n magento-test-develop 

It adds the secret to the default namespace but the custom namespace is there. And the expected behaviour should be that it adds the secret to the namespace given.

**Comment by ds-ms** [comment]
@niekappartmedia Actions from this repo are deprecated.
Try using `azure/k8s-create-secret` action instead

**Comment by niekappartmedia** [comment]
@ds-ms Thnx sorry will do that
